services:
  bot:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: sh -c "python app.py"
    env_file: .env
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DB_FILE=/home/app/data/db.sqlite
    volumes:
      - ./data/:/home/app/data
    restart: unless-stopped

